# Generated by Django 4.0.6 on 2023-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificate_id',
            field=models.CharField(default='000000', max_length=10),
        ),
    ]
