# Generated by Django 4.0.6 on 2023-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_certificate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transcript_id',
            field=models.CharField(default='000000', max_length=10),
        ),
    ]
